
-- 民用建筑设计统一标准条文表 V3.0
-- Table: civil_building_articles
DROP TABLE IF EXISTS civil_building_articles CASCADE;
DROP TABLE IF EXISTS civil_building_chapters CASCADE;

-- 章节表
CREATE TABLE civil_building_chapters (
    id SERIAL PRIMARY KEY,
    chapter_number VARCHAR(20) UNIQUE NOT NULL,
    chapter_title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 条文表
CREATE TABLE civil_building_articles (
    id SERIAL PRIMARY KEY,
    chapter_id INTEGER REFERENCES civil_building_chapters(id) ON DELETE CASCADE,
    article_number VARCHAR(50) UNIQUE NOT NULL,
    article_content TEXT NOT NULL,
    is_mandatory BOOLEAN DEFAULT FALSE,
    article_type VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX idx_civil_articles_number ON civil_building_articles(article_number);
CREATE INDEX idx_civil_articles_mandatory ON civil_building_articles(is_mandatory);
CREATE INDEX idx_civil_articles_type ON civil_building_articles(article_type);
CREATE INDEX idx_civil_articles_chapter ON civil_building_articles(chapter_id);

-- 添加注释
COMMENT ON TABLE civil_building_chapters IS '规范章节表';
COMMENT ON TABLE civil_building_articles IS '规范条文表';
COMMENT ON COLUMN civil_building_articles.article_number IS '条文编号，如1.0.1';
COMMENT ON COLUMN civil_building_articles.article_content IS '条文内容';
COMMENT ON COLUMN civil_building_articles.is_mandatory IS '是否为强制性条文';
COMMENT ON COLUMN civil_building_articles.article_type IS '条文类型';


-- 插入章节数据
INSERT INTO civil_building_chapters (chapter_number, chapter_title) VALUES
('1', '总则'),
('2', '术语'),
('3', '基本规定'),
('4', '规划控制'),
('5', '场地设计'),
('6', '建筑物设计'),
('7', '室内环境'),
('8', '建筑设备'),
('42', ''),
('52', ''),
('73', '')
;

-- 插入条文数据
INSERT INTO civil_building_articles (chapter_id, article_number, article_content, is_mandatory, article_type) VALUES
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.1', 'Classification of Civil Buildings.6 3.2 Designed Service L.ife.6 .3 Basic Requirements of Climate Region of Building .7', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.6', 'Disater Prevention and Asylum.9 4Planning Control..1() A.3 Buildling Surface Eruption..12 5 Site Planning ...16', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1', 'Architcctural Composition16', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.3', 'Vertical Design ...19 5. 1 Greening D:sign ...20)', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5', 'Layout of Pipeline Enginccring21 6 Architecture Design.23', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.7', 'Steps, Ramps and Railings .28 6. 10 Wall Detail and Deformation Joint ...33', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.12', 'Building Curtain Wall .36 6. 16 Piping Shaft. Smoke Uptake and Air Shaft ..40 7 Indoor Environment ..43', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2', 'Ventilation .44 7. 1 Acoustical Environnent.15 8 Building Implements.48', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3', 'Architecture Electric.53 8. 1 Gas ..56 Explanation of Wording in This Standard ..60 List of Quoted Standards..61 Addition: Explanation of Provisions.63 10', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '1'), '1.0.1', '为使民用建筑符合适用、经济、绿色、美观的建筑方针, 满足安全、卫生、环保等基本要求, 统一各类民用建筑的通用设 计要求,制定本标准。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '1'), '1.0.2', '本标准适用于新建、扩建和改建的民用建筑设计。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '1'), '1.0.3', '民用建筑设计除应执行国家有关法律、法规外,尚应符 合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '1'), '1.0.4', '民用建筑设计除应符合本标准外,尚应符合国家现行有 关标准的规定。 2术语', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.1', '民用建筑 civil building 供人们居住和进行公共活动的建筑的总称。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.2', '居住建筑 residential building 供人们居住使用的建筑。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.3', '公共建筑 public building 供人们进行各种公共活动的建筑。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.4', '无障碍设施 accessibility facilities 保障人员通行安全和使用便利,与民用建筑T程配套建设的 服务设施。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.5', '建筑基地 construction site 根据用地性质和使用权属确定的建筑I程项目的使用场地。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.6', '道路红线 boundary line of roads 城市道路(含居住区级道路)用地的边界线。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.7', '用地红线 property line 各类建设工程项目用地使用权属范围的边界线。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.8', '建筑控制线 building line 规划行政主管部门在道路红线、建设用地边界内。另行划定 的地面以上建(构)筑物主体不得超出的界线。', FALSE, '禁止性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.9', '建筑密度 building density:building coverage ratio 在一定用地范围内,建筑物基底面积总和与总用地面积的比 率(%)。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.10', '容积率 plot ratio: floor area ratio 在一定用地及计容范围内,建筑面积总和与用地面积的 比值。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.11', '绿地率 greening rate 在一定用地范围内,各类绿地总面积占该用地总面积的比 率(%)。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.12', '日照标准 insolation standard 根据建筑物所处的气候区、城市规模和建筑物的使用性质确 定的,在规定的日照标准日(冬至日或大寒日) 的有效日照时间 范围内。以有日照要求楼层的窗台面为计算起点的建筑外窗获得 的日照时间。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.13', '层高 storey height 建筑物各层之间以楼、地面面层(完成面)计算的垂直距 离,屋顶层由该层楼面面层(完成面)至平屋面的结构面层或至 坡顶的结构面层与外墙外皮延长线的交点计算的垂直距离。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.14', '室内净高 interior clear height 从楼、地面面层(完成面) 至吊顶或楼盖、屋盖底面之间的 有效使用空间的垂直距离。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.15', '地下室 basement 房间地平面低于室外地平面的高度超过该房间净高的1 2者 为地下室。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.16', '半地下室 semi-basement 房间地平面低于室外地平面的高度超过该房间净高的 1''3. 且不超过1/2者为半地下室。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.17', '设备层 equipment floor 建筑物中专为设置暖通、空调、给水排水和电气等的设备和 管道H供人员进入操作用的空间层。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.18', '避难层 refuge storey 在高度超过100.0m 的高层建筑中,用于人员在火灾时暂时 躲避火灾及其烟气危害的楼层。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.19', '架空层 open floor 用结构支撑且无外围护墙体的开敞空间。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.20', '台阶 step 连接室外或室内的不同标高的楼面、地面,供人行的阶梯式 交通道。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.21', '临空高度 the vertical height between two open space 相邻开敞空间有高差时,上下楼地面之间的垂直距离。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.22', '坡道 ramp 连接室外或室内的不同标高的楼面、地面,供人行或车行的 斜坡式交通道。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.23', '栏杆 railing 具有一定的安全高度,用以保障人身安全或分隔空间用的防 护分隔构件。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.24', '楼梯 stair 由连续行走的梯级、休息平台和维护安全的栏杆(或栏板)、 扶手以及相应的支承结构组成的作为楼层之间垂直交通用的建筑 部件。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.25', '变形缝 deformation joint 为防止建筑物在外界因素作用下,结构内部产生附加变形和 应力, 导致建筑物开裂、碰撞甚至破坏而预留的构造缝、包括伸 缩缝、沉降缝和抗震缝。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.26', '建筑幕墙 building curtain wall 由面板与支承结构体系(支承装置与支承结构) 组成的可相 对主体结构有一定位移能力或自身有一定变形能力、不承担主体 结构所受作用的建筑外围护墙。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.27', '吊顶 suspended ceiling 悬吊在房屋屋顶或楼板结构下的顶棚。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.28', '管道井pipe shaft 建筑物中用于布置坚向设备管线及设备的坚向井道。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.29', '烟道 smoke uptake; smoke flue 排放各种烟气的管道、井道。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.30', '通风道 air shaft 排除室内不良气体或者输送新鲜空气的管道、井道。', FALSE, '禁止性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.31', '装修 decoration; finishing 以建筑物主体结构为依托,对建筑内、外空间进行的细部加 工和艺术处理。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.32', '采光 daylighting 为保证人们生活、工作或生产活动具有适宜的光环境,使建 筑物内部使用空间取得的天然光照度满足使用、安全、舒适、美 观等要求的措施。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.33', '采光系数 daylight factor 在室内给定平面上的一点,由直接或间接地接收来自假定和 已知天空亮度分布的天空漫射光而产生的照度与同一时刻该天空 半球在室外无遮挡水平面上产生的天空漫射光照度之比。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.34', '采光系数标准值 standard value of daylight factor 在规定的室外天然光设计照度下,满足视觉功能要求时的采 光系数值。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.35', '通风 ventilation 为保证人们生活、工作或生产活动具有适宜的空气环境,采 用自然或机械方法,对建筑物内部使用空间进行换气,使空气质 量满足卫生、安全、舒适等要求的技术。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.36', '噪声 noise 影响人们正常生活、工作、学习、休息,甚至损害身心健康 的外界干扰声。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '2'), '2.0.37', '建筑连接体 building connection 跨越道路红线、建设用地边界建造,连接不同用地之间地下 或地上的建筑物。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.1.1', '民用建筑按使用功能可分为居住建筑和公共建筑两大类。 其中, 居住建筑可分为住宅建筑和宿舍建筑。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.12', '民用建筑按地上建筑高度或层数进行分类应符合下列 规定: 1 建筑高度不大于27.0m 的住宅建筑、建筑高度不大于 21.0m 的公共建筑及建筑高度大于21.0m 的单层公共建筑为低 层或多层民用建筑; 2建筑高度大于27.0m 的住宅建筑和建筑高度大于24.0m 的非单层公共建筑,且高度不大于100.0m 的.为高层民用 建筑; 3 建筑高度大于100.0m 为超高层建筑。 注:建筑防火设计应符合现行国家标准《建筑设计防火规范》GB 50016有关建筑高度和层数计算的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.1.3', '民用建筑等级分类划分应符合国家现行有关标准或行业 主管部门的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.2', '设计使用年限', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.2.1', '民用建筑的设计使用年限应符合表3.2.1 的规定。 表3.2.1 设计使用年限分类 类别 设计使用年限(年) 示例 1 5 临时性建筑 2 25 易于替换结构构件的建筑 3 50 普通建筑和构筑物 1 100 纪念性建筑和特别重要的建筑 注:此表依据《建筑结构可靠性设计统一标准》 GB50068.并与其协调一致。', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.3', '建筑气候分区对建筑基本要求', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.3.1', '建筑气候分区对建筑的基本要求应符合表3.3.1 的规定。 表3.3.1 不同区划对建筑的基本要求 建筑气候 区划名称 热工区划 名称 建筑气候区划主要指标 建筑基本要求 1.建筑物必须充分满足冬季 1 IA IC ID [B 严寒地区 7月平均相对湿度≥50% 1月平均气温≤-10°C 7月平均气温≤25°C 保温、防寒、防冻等要求; 积雪对建筑物的危害: 2. |A、IB区应防止冻土、 3. I B、∫C、D区的西 部.建筑物应防冰雹、防风沙 1.建筑物应满足冬季保温、 防寒、防冻等要求,夏季部分 II IA B 寒冷地区 1月平均气温-10°C~0° 7月平均气温 18^°C~28°C 地区应兼顾防热: 2. II A 区建筑物应防热、防 潮、防暴风雨,沿海地带应防 盐雾侵蚀 1.建筑物应满足复季防热、 遮阳、通风降温要求。并应兼 顾冬季防寒; I A IB IIC 夏热冬冷 地|区 7月平均气温25°C~30°C 1月平均气温0^°C~10^°C 防洪、防雷电等要求: 击及盐雾侵蚀: 2.建筑物应满足防雨、防潮、 3. IIA区应防台风、暴雨袭 4. IIB、IC区北部冬季积雪 地区建筑物的屋面应有防积 危害的措施 1.建筑物必须满足夏季遮阳、 通风、防热要求: Ʌ AA NB 夏热冬暖 地区 7月平均气温 25~29°C 1月平均气温 -10^° 防洪、防雷电: 2. 建筑物应防暴雨、防潮、 3. | A区应防台风、暴雨袭 击及盐雾侵蚀 续表3.3.1 建筑气候 区划名称 热T区划 名称 建筑气候区划主要指标 建筑基本要求 1.建筑物应满足防雨和通风 V VB VA 温和地区 7月平均气温 18°C~25°C 1月平均气温0°C~13°C 要求: 2.VA区建筑物应注意防寒. VB区应特别注意防雷电 V VA VB 严寒地区 1月平均气温0°C~-22°C 7月平均气温<18°C 并应特别注意防风沙: 防寒、防冻的要求; 筑物地基及地下管道的影响。 2. VIA、VB区应防冻土对建 1.建筑物应充分满足保温、 VC 寒冷地|区 3.VC区的东部,建筑物应 防雷电 1.建筑物必须充分满足保温、 VIA VB 严寒地区 防寒、防冻的要求: 2.除VID区外。应防冻土对 VC 建筑物地基及地下管道的危害: 1月平均气温-5°C~-20°C 3. \IB区建筑物应特别注意 MII 7月平均气温≥18°C 积雪的危害; 7月平均相对湿度<50 % 4.VIC 区建筑物应特别注意 防风沙, 夏季兼顾防热: D 寒冷地区 5. VIID区建筑物应注意夏季 防热,吐鲁番盆地应特别注意 隔热、降温 3.4建筑与环境', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.4.1', '建筑与自然环境的关系应符合下列规定: 严格控制对自然和生态环境的不利影响; .4.2 建筑与人文环境的关系应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.5', '建筑模数', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.5.1', '建筑设计应符合现行国家标准《建筑模数协调标准》 GB/T 50002 的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.5.2', '建筑平面的柱网、开间、进深、层高、门窗洞口等主要 定位线尺寸,应为基本模数的倍数,并应符合下列规定: 1 平面的开间进深、柱网或跨度、门窗洞口宽度等主要定 位尺寸, 宜采用水平扩大模数数列 2nM、3nM( n 为自然数); 2 层高和门窗洞口高度等主要标注尺寸,宜采用坚向扩大 模数数列 \(n M\) ( n 为自然数)。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.6.1', '建筑防灾避难场所或设施的设置应满足城乡规划的总体 要求,并应遵循场地安全、交通便利和出人方便的原则。 ..2 建筑设计应根据灾害种类,合理采取防灾、减灾及避难 的相应措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.63', '防灾避难设施应因地制宜、平灾结合,集约利用资源。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.6.4', '防灾避难场所及设施应保障安全、长期备用、便于管理。 并应符合无障碍的相关规定。 4规划控制 4.1城乡规划及城市设计', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.1.1', '建筑项目的用地性质、容积率、建筑密度、绿地率、建 筑高度及其建筑基地的年径流总量控制率等控制指标、应符合所 在地控制性详细规划的有关规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.1.2', '建筑及其环境设计应满足城乡规划及城市设计对所在区 域的目标定位及空间形态、景观风貌、环境品质等控制和引导要 求.并应满足城市设计对公共空间、建筑群体、园林景观、市政 等环境设施的设计控制要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.1.3', '建筑设计应注重建筑群体空间与自然山水环境的融合与 协调、历史文化与传统风貌特色的保护与发展、公共活动与公共 空间的组织与塑造,并应符合下列规定: 4建筑基地内的道路、停车场、硬质地面宜采用透水铺装:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.2', '建筑基地', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '42'), '42.1', '建筑基地应与城市道路或镇区道路相邻接.否则应设置 连接道路,并应符合下列规定: 10 1 当建筑基地内建筑面积小于或等于 \(3000 ~m^{2}\) 时,其连接道 路的宽度不应小于 4. 0m; 2 当建筑基地内建筑面积大于 \(3000 ~m^{2}\) .且只有一条连接道 路时。其宽度不应小于7. 0m; 当有两条或两条以上连接道路时。 单条连接道路宽度不应小于 1. 0m。 3 当相邻基地的建筑物毗邻建造时,应符合现行国家标准 《建筑设计防火规范》GB 50016 的有关规定: 4新建建筑物或构筑物应满足周边建筑物的日照标准:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.2.4', '建筑基地机动车出入口位置。应符合所在地控制性详细 规划:并应符合下列规定: 1 中等城市、大城市的主干路交叉11.自道路红线交叉点 起沿线70.0m 范围内不应设置机动车出入口: 2 距人行横道、人行天桥、人行地道(包括引道、引桥) 的最近边缘线不应小于5.0m; 3 距地铁出入口、公共交通站台边缘不应小于15.0m; 11 人口最近边缘不应小于20.0m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.2.5', '大型、特大型交通、文化、体育、娱乐、商业等人员密 集的建筑基地应符合下列规定: 1 建筑基地与城市道路邻接的总长度不应小于建筑基地周 长的1/6; 2 建筑基地的出人口不应少于2个,且不宜设置在同一条 城市道路上;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.3', '建筑突出物', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.3.1', '除骑楼、建筑连接体、地铁相关设施及连接城市的管 线、管沟、管廊等市政公共设施以外,建筑物及其附属的下列设 施不应突出道路红线或用地红线建造: 2 地上设施, 应包括门廊、连廊、阳台、室外楼梯、凸窗、 空调机位、雨篷、挑檐、装饰构架、固定遮阳板、台阶、坡道、 花池、围墙、平台、散水明沟、地下室进风及排风口、地下室出 入口、集水井、采光井、烟囱等。', TRUE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.3.2', '经当地规划行政主管部门批准,既有建筑改造T程必须 突出道路红线的建筑突出物应符合下列规定: 1在人行道上空: 1) 2.5m以下,不应突出凸窗、窗扇、窗罩等建筑构件; 2. 5m 及以上突出凸窗、窗扇、窗罩时,其深度不应 大于0.6m。 2) 2.5m以下,不应突出活动遮阳;2.5m及以上突出活 12 动遮阳时,其宽度不应大于人行道宽度减1.0m,并不 应大于3.0m。 3) .0m以下,不应突出雨篷、挑檐;3.0m及以上突出 雨篷、挑檐时,其突出的深度不应大于2.0m。 4) .0m以下,不应突出空调机位;3.0m及以上突出空 调机位时,其突出的深度不应大于0. 6m。 2 在无人行道的路面上空,4.0m以下不应突出凸窗、窗 扇、窗罩、空调机位等建筑构件; 4. 0m 及以上突出凸窗、窗 扇、窗罩、空调机位时,其突出深度不应大于0.6m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.33', '除地下室、窗井、建筑人口的台阶、坡道、雨篷等以外, 建(构)筑物的主体不得突出建筑控制线建造。', FALSE, '禁止性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.3.4', '治安岗、公交候车亭,地铁、地下隧道、过街天桥等相 关设施,以及临时性建(构)筑物等。当确有需要,且不影响交 通及消防安全,应经当地规划行政主管部门批准,可突人道路红 线建造。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.3.5', '骑楼、建筑连接体和沿道路红线的悬挑建筑的建造,不 应影响交通、环保及消防安全。在有顶盖的城市公共空间内,不 应设置直接排气的空调机、排气扇等设施或排出有害气体的其他 通风系统。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.4', '建筑连接体', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.4.1', '经当地规划及市政主管部门批准,建筑连接体可跨越道 路红线、用地红线或建筑控制线建设,属于城市公共交通性质的 出人口可在道路红线范围内设置。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.4.2', '建筑连接体可在地下、裙房部位及建筑高空建造,其建 设应统筹规划, 保障城市公众利益与安全,并不应影响其他人 流、车流及城市景观。 13 .4.3 地下建筑连接体应满足市政管线及其他基础设施等建设 要求。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.4.4', '交通功能的建筑连接体,其净宽不宜大于9.0m,地上的 净宽不宜小于3.0m.地下的净宽不宜小于4.0m。其他非交通功 能连接体的宽度,宜结合建筑功能按人流疏散需求设置。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.4.5', '建筑连接体在满足其使用功能的同时,还应满足消防疏 散及结构安全方面的要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.5', '建筑高度', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.5.1', '建筑高度不应危害公共空间安全和公共卫生,且不宜影 响景观。下列地区应实行建筑高度控制。并应符合下列规定: 注:建筑高度控制尚应符合所在地城市规划行政主管部门和有关专业 部门的规定。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.5.2', '建筑高度的计算应符合下列规定: 1本标准第1.5.1条第3款、第4 款控制区内建筑,建筑 高度应以绝对海拔高度控制建筑物室外地面至建筑物和构筑物最 高点的高度。 2非本标准第.5.1条第3 款、第4 款控制区内建筑,平 屋顶建筑高度应按建筑物主人口场地室外设计地面至建筑女儿墙 顶点的高度计算, 无女儿墙的建筑物应计算至其屋面檐口;坡屋 14 顶建筑高度应按建筑物室外地面至屋檐和屋脊的平均高度计算; 当同一座建筑物有多种屋面形式时,建筑高度应按上述方法分别 计算后取其中最大值;下列突出物不计人建筑高度内: 1) 局部突出屋面的楼梯间、电梯机房、水箱间等辅助用 房占屋顶平面面积不超过1/4 者; 2)突出屋面的通风道、烟囱、装饰构件、花架、通信设 施等; 3) 空调冷却塔等设备。 15', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1.1', '建筑布局应使建筑基地内的人流、车流与物流合理分流, 防止干扰,并应有利于消防、停车、人员集散以及无障碍设施的 设置。 5..2 建筑间距应符合下列规定: 1 建筑间距应符合现行国家标准《建筑设计防火规范》GB 50016 的规定及当地城市规划要求; 2 建筑间距应符合本标准第7.1节建筑用房天然采光的规 定,有日照要求的建筑和场地应符合国家相关日照标准的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1.3', '建筑布局应根据地域气候特征,防止和抵御寒冷、暑热、 疾风、暴雨、积雪和沙尘等灾害侵袭,并应利用自然气流组织好 通风,防止不良小气候产生。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1.4', '根据噪声源的位置、方向和强度、应在建筑功能分区、 道路布置、建筑朝向、距离以及地形、绿化和建筑物的屏障作用 等方面采取综合措施, 防止或降低环境噪声。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1.5', '建筑物与各种污染源的卫生距离,应符合国家现行有关 卫生标准的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1.6', '建筑布局应按国家及地方的相关规定对文物古迹和古树 名木进行保护, 避免损毁破坏。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2', '道路与停车场', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.1', '基地道路应符合下列规定: 16 利用楼梯间,其间距不宜大于80. 0m; 5 基地内宜设人行道路,大型、特大型交通、文化、娱乐、 商业、体育、医院等建筑,居住人数大于5000人的居住区等车 流量较大的场所应设人行道路。 1 单车道路宽不应小于4. 0m,双车道路宽住宅区内不应小 于6.0m, 其他基地道路宽不应小于7.0m; 3 人行道路宽度不应小于1.5m,人行道在各路口、人口处 的设计应符合现行国家标准《无障碍设计规范》GB 50763的相 关规定; 4 道路转弯半径不应小于3.0m,消防车道应满足消防车最 小转弯半径要求; 5 尽端式道路长度大于120.0m时,应在尽端设置不小于 12. 0m×12. 0m 的回车场地。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.3', '基地道路与建筑物的关系应符合下列规定: 1 当道路用作消防车道时,其边缘与建(构) 筑物的最小 距离应符合现行国家标准《建筑设计防火规范》GB 50016的相 关规定;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.4', '建筑基地内地下机动车车库出入口与连接道路间宜设置 缓冲段, 缓冲段应从车库出入口坡道起坡点算起,并应符合下列 规定: 17 于5.5m; 2 当出入口与基地道路垂直时,缓冲段长度不应小于 5.5m; 3 当出入口与基地道路平行时,应设不小于5.5m长的缓 冲段再汇人基地道路; 4 当出人口直接连接基地外城市道路时.其缓冲段长度不 宜小于7.5m。 5..5 室外机动车停车场应符合下列规定: 1 停车场地应满足排水要求,排水坡度不应小于0.3%; 3 停车场应设置无障碍停车位,且设置要求和停车位数量 应符合现行国家标准《无障碍设计规范》GB 50763的相关规定; 4停车场应结合绿化合理布置,可利用乔木遮阳。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.6', '室外机动车停车场的出入口数量应符合下列规定: 1 当停车数为50 辆及以下时,可设1个出入口,宜为双向 行驶的出人口; 2 当停车数为51辆~300 辆时,应设置2个出人口。宜为 双向行驶的出入口; 3 当停车数为301 辆~500 辆时,应设置2个双向行驶的 出入口; 4 当停车数大于500辆时,应设置3个出人口,宜为双向 行驶的出入口。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.7', '室外机动车停车场的出入口设置应符合下列规定: 1 大于300 辆停车位的停车场,各出入口的间距不应小 于15.0m; 2 单向行驶的出入口宽度不应小于4.0m,双向行驶的出入 口宽度不应小于7.0m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.8', '室外非机动车停车场应设置在基地边界线以内,出入口 不宜设置在交叉路口附近,停车场布置应符合下列规定: 1停车场出入口宽度不应小于2.0m; 18 2 停车数大于等于300 辆时,应设置不少于2个出入口; 3 停车区应分组布置,每组停车区长度不宜超过20.0m。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.3.1', '建筑基地场地设计应符合下列规定: 1 当基地自然坡度小于5%时,宜采用平坡式布置方式; 当大于8%时,宜采用台阶式布置方式,台地连接处应设挡墙或 护坡; 基地临近挡墙或护坡的地段,宜设置排水沟,且坡向排水 沟的地面坡度不应小于1%。 2 基地地面坡度不宜小于0.2%;当坡度小于0.2%时.宜 采用多坡向或特殊措施排水。 3 场地设计标高不应低于城市的设计防洪、防涝水位标高; 沿江、河、湖、海岸或受洪水、潮水泛滥威胁的地区、除设有可 靠防洪堤、坝的城市、街区外,场地设计标高不应低于设计洪水 位0.5m。否则应采取相应的防洪措施:有内涝威胁的用地应采 取可靠的防、排内涝水措施,否则其场地设计标高不应低于内涝 水位0.5m。 5 场地设计标高宜比周边城市市政道路的最低路段标高高 0. 2m以上;当市政道路标高高于基地标高时,应有防止客水进 入基地的措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.3.2', '建筑基地内道路设计坡度应符合下列规定: 1 基地内机动车道的纵坡不应小于0.3%.且不应大于 8 %。当采用8%坡度时, 其坡长不应大于200. 0m。当遇特殊困 难纵坡小于0.3%时,应采取有效的排水措施;个别特殊路段, 坡度不应大于11%,其坡长不应大于100.0m,在积雪或冰冻地 19 区不应大于6%,其坡长不应大于350. 0m; 横坡宜为1%~2%。 2 基地内非机动车道的纵坡不应小于0.2%,最大纵坡不 宜大于 2.5 %; 困难时不应大于3.5%,当采用3.5%坡度时, 其坡长不应大于150. 0m; 横坡宜为1%~2%。 3 基地内步行道的纵坡不应小于0.2%,且不应大于8%, 积雪或冰冻地区不应大于 4%; 横坡应为1%~2%;当大于极限 坡度时,应设置为台阶步道。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.3.3', '建筑基地地面排水应符合下列规定:', FALSE, '强制性条文')
;

INSERT INTO civil_building_articles (chapter_id, article_number, article_content, is_mandatory, article_type) VALUES
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.3.4', '下沉庭院周边和车库坡道出入口处,应设置截水沟。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.3.5', '建筑物底层出入口处应采取措施防止室外地面雨水回流。 5.4绿 化', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.4.1', '绿化设计应符合下列规定: 1绿地指标应符合当地控制性详细规划及城市绿地管理的 有关规定。 20', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.4.2', '地下建筑顶板上的绿化工程应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.1', '工程管线宜在地下敷设;在地上架空敷设的工程管线及 工程管线在地上设置的设施,必须满足消防车辆通行及扑救的要 求,不得妨碍普通车辆、行人的正常活动,并应避免对建筑物、 景观的影响。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.2', '与市政管网衔接的工程管线,其平面位置和竖向标高均 应采用城市统一的坐标系统和高程系统。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.3', '工程管线的敷设不应影响建筑物的安全,并应防止工程 管线受腐蚀、沉陷、振动、外部荷载等影响而损坏。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.4', '在管线密集的地段,应根据其不同特性和要求综合布置, 宜采用综合管廊布置方式。对安全、卫生、防干扰等有影响的工 程管线不应共沟或靠近敷设。互有干扰的管线应设置在综合管廊 的不同沟(室)内。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.5', '地下工程管线的走向宜与道路或建筑主体相平行或垂直。 工程管线应从建筑物向道路方向由浅至深敷设。干管宜布置在主 要用户或支管较多的一侧,工程管线布置应短捷、转弯少,减少 与道路、铁路、河道、沟渠及其他管线的交叉,困难条件下其交 角不应小于45^°。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.6', '与道路平行的工程管线不宜设于车行道下;当确有需要 时,可将埋深较大、翻修较少的工程管线布置在车行道下。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.7', '工程管线之间的水平、垂直净距及埋深、工程管线与建 (构)筑物、绿化树种之间的水平净距应符合国家现行有关标准 21 的规定。当受规划、现状制约,难以满足要求时,可根据实际情 况采取安全措施后减少其最小水平净距。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.8', '抗震设防烈度7度及以上地震区、多年冻土区、严寒地 区、湿陷性黄土地区及膨胀土地区的室外T程管线、应符合国家 现行有关标准的规定。 .5.9 各种工程管线不应在平行方向重叠直埋敷设。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.10', '工程管线的检查井井盖宜有锁闭装置。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.11', '当基地进行分期建设时,应对T.程管线做整体规划。前 期的工程管线敷设不得影响后期的工程建设。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.12', '与基地无关的可燃易爆的市政工程管线不得穿越基地。 当基地内已有此类管线时,基地内建筑和人员密集场所应与此类 管线保持安全距离。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.13', '当室外消防水池设有消防车取水口(井)时,应设置消 防车到达取水口(井)的消防车道和消防车回车场地。 22', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.1', '建筑标定人数的确定', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.1.1', '有固定座位等标明使用人数的建筑,应按照标定人数为 基数计算配套设施、疏散通道和楼梯及安全出口的宽度。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.1.2', '对无标定人数的建筑应按国家现行有关标准或经调查分 析确定合理的使用人数、并应以此为基数计算配套设施、疏散通 道和楼梯及安全出口的宽度。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.1.3', '多功能用途的公共建筑中,各种场所有可能同时使用同 一出口时,在水平方向应按各部分使用人数叠加计算安全疏散出 口和疏散楼梯的宽度;在垂直方向,地上建筑应按楼层使用人数 最多一层计算以下楼层安全疏散楼梯的宽度,地下建筑应按楼层 使用人数最多一层计算以上楼层安全疏散楼梯的宽度。 6.2平面布置', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.2.1', '建筑平面应根据建筑的使用性质、功能、工艺等要求合 理布局,并具有一定的灵活性。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.22', '根据使用功能,建筑的使用空间应充分利用日照、采光、 通风和景观等自然条件。对有私密性要求的房间,应防止视线 干扰。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.2.3', '建筑出人口应根据场地条件、建筑使用功能、交通组织 以及安全疏散等要求进行设置。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.2.4', '地震区的建筑平面布置宜规整。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.3', '层高和室内净高', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.3.1', '建筑层高应结合建筑使用功能、工艺要求和技术经济条 件等综合确定,并符合国家现行相关建筑设计标准的规定。 23', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.3.2', '室内净高应按楼地面完成面至吊顶、楼板或梁底面之间 的垂直距离计算;当楼盖、屋盖的下悬构件或管道底面影响有效 使用空间时,应按楼地面完成面至下悬构件下缘或管道底面之间 的垂直距离计算。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.3.3', '建筑用房的室内净高应符合国家现行相关建筑设计标准 的规定,地下室、局部夹层、走道等有人员正常活动的最低处净 高不应小于2.0m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4', '地下室和半地下室', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.1', '地下室和半地下室应合理布置地下停车库、地下人防工 程、各类设备用房等功能空间及其出入口,出入口、进排风竖井 的地面建(构)筑物应与周边环境协调。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.2', '地下建筑连接体的设计应符合城市地下空间规划的相关 规定, 并应做到导向清晰、流线简捷,防火分区与管理等界线 明确。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.3', '地下室和半地下室的建造不得影响相邻建(构) 筑物、 市政管线等的安全。', FALSE, '禁止性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.4', '当日常为人员使用时,地下室和半地下室应满足安全、 卫生及节能的要求,且宜利用窗井或下沉庭院等进行自然通风和 采光。其他功能的地下室和半地下室应符合国家现行有关标准的 规定。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.5', '地下室和半地下室外围护结构应规整,其防水等级及技 术要求应符合现行国家标准《地下工程防水技术规范》GB 50108 的规定,并应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.6', '地下室和半地下室的耐火等级、防火分区、安全疏散、 防排烟设施、房间内部装修等应符合现行国家标准《建筑设计防 火规范》GB 50016 的有关规定。 24', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.4.7', '地下室不应布置居室;当居室布置在半地下室时, 必须 采取满足采光、通风、日照、防潮、防霉及安全防护等要求的相 关措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.5', '设备层、避难层和架空层', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.5.1', '设备层设置应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.5.2', '避难层的设置应符合现行国家标准《建筑设计防火规范》 GB 50016 的规定,并应符合下列规定: 2 避难层的净高不应低于2.0m。当避难层兼顾其他功能 时,应根据功能空间的需要来确定净高。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.5.3', '有人员正常活动的架空层的净高不应低于2.0m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6', '厕所、卫生间、盥洗室、浴室和母婴室', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6.1', '厕所、卫生间、盥洗室和浴室的位置应符合下列规定: 1 厕所、卫生间、盥洗室和浴室应根据功能合理布置, 位 置选择应方便使用、相对隐蔽,并应避免所产生的气味、潮气、 噪声等影响或干扰其他房间。室内公共厕所的服务半径应满足不 同类型建筑的使用要求, 不宜超过 50. 0m。 25 厅、医疗用房等有较高卫生要求用房的直接上层、应避免布置厕 所、卫生间、盥洗室、浴室等有水房间、否则应采取同层排水和 严格的防水措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6.2', '卫生器具配置的数量应符合国家现行相关建筑设计标准的 规定。男女厕位的比例应根据使用特点、使用人数确定。在男女 使用人数基本均衡时,男厕厕位(含大、小便器)与女厕厕位数 量的比例宜为1:1~1:1.5;在商场、体育场馆、学校、观演建 筑、交通建筑、公园等场所,厕位数量比不宜小于1:1.5~1:2。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6.3', '厕所、卫生间、盥洗室和浴室的平面布置应符合下列 规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6.4', '厕所和浴室隔间的平面尺寸应根据使用特点合理确定, 并不应小于表 6.6.4 的规定。交通客运站和大中型商店等建筑物 的公共厕所,宜加设婴儿尿布台和儿童固定座椅。交通客运站厕 位隔间应考虑行李放置空间,其进深尺寸宜加大0. 2m, 便于放 置行李。儿童使用的卫生器具应符合幼儿人体工程学的要求。无 障碍专用浴室隔间的尺寸应符合现行国家标准《无障碍设计规 范》GB 50763 的规定。 表6.6.4 厕所和浴室隔间的平面尺寸 类别 平面尺寸(宽度m×深度m) 外开门的厕所隔间 0.9×1.2(蹲便器) 0.9×1.3(坐便器) 26 续表6.6.4 类别 平面尺寸(宽度mX深度m) 内开门的厕所隔间 0.9×1.4(蹲便器) 0.9×1.5(坐便器) 医院患者专用厕所隔间 (外开门) 1.1×1.5(门闩应能里外开启) 无障碍厕所隔间(外开门) 1.5×2.0(不应小于1.0×1.8) 外开门淋浴隔间 1.0×1.2(或1.1×1.1) 内设更衣凳的淋浴隔间 1.0×(1.0+0.6)', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6.5', '卫生设备间距应符合下列规定: 1 洗手盆或盥洗槽水嘴中心与侧墙面净距不应小于0.55m; 居住建筑洗手盆水嘴中心与侧墙面净距不应小于0. 35m。 2 并列洗手盆或盥洗槽水嘴中心间距不应小于0. 7m。 3 单侧并列洗手盆或盥洗槽外沿至对面墙的净距不应小于 1.25m;居住建筑洗手盆外沿至对面墙的净距不应小于0.6m。 4双侧并列洗手盆或盥洗槽外沿之间的净距不应小于 1.8m。 5 并列小便器的中心距离不应小于0. 7m, 小便器之间宜加 隔板,小便器中心距侧墙或隔板的距离不应小于0.35m,小便器 上方宜设置搁物台。 6 单侧厕所隔间至对面洗手盆或盥洗槽的距离,当采用内 开门时,不应小于1.3m;当采用外开门时,不应小于1.5m。 7 单侧厕所隔间至对面墙面的净距,当采用内开门时不应 小于1.1m,当采用外开门时不应小于1.3m;双侧厕所隔间之间 的净距, 当采用内开门时不应小于1. 1m, 当采用外开门时不应 小于1.3m。 8 单侧厕所隔间至对面小便器或小便槽的外沿的净距,当 采用内开门时不应小于1.1m,当采用外开门时不应小于1.3m; 小便器或小便槽双侧布置时,外沿之间的净距不应小于1.3m 27 (小便器的进深最小尺寸为350mm)。 9 浴盆长边至对面墙面的净距不应小于0.65m;无障碍盆 浴间短边净宽度不应小于2. 0m, 并应在浴盆一端设置方便进人 和使用的坐台,其深度不应小于0. 4m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.6.6', '在交通客运站、高速公路服务站、医院、大中型商店、 博览建筑、公园等公共场所应设置母婴室,办公楼等工作场所的 建筑物内宜设置母婴室。母婴室应符合下列规定: 1 母婴室应为独立房间且使用面积不宜低于 \(10. 0 ~m^{2}\) ;', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.7.1', '台阶设置应符合下列规定: 1 公共建筑室内外台阶踏步宽度不宜小于0.3m,踏步高度 不宜大于0.15m,且不宜小于0.lm; 3 室内台阶踏步数不宜少于2级,当高差不足2级时,宜 按坡道设置; 4 台阶总高度超过0.7m时,应在临空面采取防护设施;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.7.2', '坡道设置应符合下列规定: 1 室内坡道坡度不宜大于1:8,室外坡道坡度不宜大于 1:10; 2 当室内坡道水平投影长度超过15.0m时,宜设休息平 台,平台宽度应根据使用功能或设备尺寸所需缓冲空间而定; 4 当坡道总高度超过0. 7m时,应在临空面采取防护设施; 28 范》GB 50763 的有关规定; 6机动车和非机动车使用的坡道应符合现行行业标准《车 库建筑设计规范》JGJ 100 的有关规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.7.3', '阳台、外廊、室内回廊、内天井、上人屋面及室外楼梯 等临空处应设置防护栏杆, 并应符合下列规定: 1 栏杆应以坚固、耐久的材料制作,并应能承受现行国家 标准《建筑结构荷载规范》GB 50009及其他国家现行相关标准 规定的水平荷载。 2 当临空高度在24.0m 以下时,栏杆高度不应低于 1.05m; 当临空高度在 24.0m 及以上时,栏杆高度不应低于 1.1m。上人屋面和交通、商业、旅馆、医院、学校等建筑临开 敞中庭的栏杆高度不应小于1. 2m。 3 栏杆高度应从所在楼地面或屋面至栏杆扶手顶面垂直高 度计算,当底面有宽度大于或等于0. 22m,且高度低于或等于 0. 45m 的可踏部位时,应从可踏部位顶面起算。 4 公共场所栏杆离地面0.1m 高度范围内不宜留空。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.7.4', '住宅、托儿所、幼儿园、中小学及其他少年儿童专用活 动场所的栏杆必须采取防止攀爬的构造。当采用垂直杆件做栏杆 时,其杆件净间距不应大于0.11m。', TRUE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8', '楼 梯', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.1', '楼梯的数量、位置、梯段净宽和楼梯间形式应满足使用 方便和安全疏散的要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.2', '当一侧有扶手时,梯段净宽应为墙体装饰面至扶手中心 线的水平距离,当双侧有扶手时, 梯段净宽应为两侧扶手中心线 之间的水平距离。当有凸出物时, 梯段净宽应从凸出物表面 算起。', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.3', '梯段净宽除应符合现行国家标准《建筑设计防火规范》 GB 50016 及国家现行相关专用建筑设计标准的规定外,供日常 主要交通用的楼梯的梯段净宽应根据建筑物使用特征, 按每股人 29 流宽度为0.55m+(0~0. 15)m 的人流股数确定,并不应少于 两股人流。(0~0. 15)m 为人流在行进中人体的摆幅,公共建筑 人流众多的场所应取上限值。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.4', '当梯段改变方向时,扶手转向端处的平台最小宽度不应 小于梯段净宽,并不得小于1. 2m。当有搬运大型物件需要时, 应适量加宽。直跑楼梯的中间平台宽度不应小于0. 9m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.5', '每个梯段的踏步级数不应少于3级,且不应超过18级。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.6', '楼梯平台上部及下部过道处的净高不应小于2.0m, 梯段 净高不应小于2.2m。 注:梯段净高为自踏步前缘 (包括每个梯段最低和最高一级踏步前缘 线以外0. 3m 范围内) 量至上方突出物下缘间的垂直高度。', TRUE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.7', '楼梯应至少于一侧设扶手,梯段净宽达三股人流时应两 侧设扶手, 达四股人流时宜加设中间扶手。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.8', '室内楼梯扶手高度自踏步前缘线量起不宜小于0.9m。楼 梯水平栏杆或栏板长度大于0. 5m时,其高度不应小于1.05m。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.9', '托儿所、幼儿园、中小学校及其他少年儿童专用活动场 所,当楼梯井净宽大于0. 2m时, 必须采取防止少年儿童坠落的 措施。', TRUE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.10', '楼梯踏步的宽度和高度应符合表6.8.10 的规定。 表6.8.10 楼梯踏步最小宽度和最大高度(m) 楼梯类别 最小宽度 最大高度 住宅公共楼梯 0.260 0.175 住宅楼梯 住宅套内楼梯 0.220 0.200 小学宿舍楼梯 0.260 0.150 宿舍楼梯 其他宿舍楼梯 0.270 0.165 住宅建筑楼梯 0.300 0.150 老年人建筑楼梯 公共建筑楼梯 0.320 0.130 托儿所、幼儿园楼梯 0.260 0.130 30 续表6.8.10 楼梯类别 最小宽度 最大高度 小学校楼梯 0.260 0.150 人员密集且坚向交通繁忙的建筑和大、 中学校楼梯 0.280 0.165 其他建筑楼梯 0.260 0.175 超高层建筑核心筒内楼梯 0.250 0.180 检修及内部服务楼梯 0.220 0.200 注: 螺旋楼梯和扇形踏步离内侧扶手中心0. 250m 处的踏步宽度不应小于0. 220m。', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.11', '梯段内每个踏步高度、宽度应一致,相邻梯段的踏步高 度、宽度宜一致。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.12', '当同一建筑地上、地下为不同使用功能时,楼梯踏步高 度和宽度可分别按本标准表 6. 8.10 的规定执行。', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.13', '踏步应采取防滑措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.8.14', '当专用建筑设计标准对楼梯有明确规定时,应按国家现 行专用建筑设计标准的规定执行。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.9', '电梯、自动扶梯和自动人行道', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.9.1', '电梯设置应符合下列规定: 3 高层公共建筑和高层宿舍建筑的电梯台数不宜少于2台, 12 层及12层以上的住宅建筑的电梯台数不应少于2 台,并应符 合现行国家标准《住宅设计规范》GB 50096的规定; 4 电梯的设置, 单侧排列时不宜超过4台.双侧排列时不 宜超过2排×4台; 5 高层建筑电梯分区服务时,每服务区的电梯单侧排列时 不宜超过4 台,双侧排列时不宜超过2排×4 台: 31 6 当建筑设有电梯目的地选层控制系统时,电梯单侧排列 或双侧排列的数量可超出本条第4 款、第5 款的规定合理设置; 7 电梯候梯厅的深度应符合表6.9.1 的规定; 表6.9.1 候梯厅深度 电梯类别 布置方式 候梯厅深度 单台 ≥B. 且≥1.5m 住宅电梯 多台单侧排列 ≥Bmx⋅且≥1.8m 多台双侧排列 ≥相对电梯 Bm x之和, <3.5m 单台 ≥1.5B,且≥1. 8m 公共建筑电梯 多台单侧排列 当电梯群为4 台时应 ≥2. 4m ≥5Bmx·1≥2. 0m 多台双侧排列 ≥相对电梯 B_n x之和, 1<4.5m 单台 ≥1.5B 病床电梯 多台单侧排列 ≥1.5Bm0x 多台双侧排列 ≥相对电梯 B1t x 之和 注: B 为轿厢深度, \(B_{max }\) 为电梯群中最大轿厢深度。 11 消防电梯的布置应符合现行国家标准《建筑设计防火规 范》GB 50016 的有关规定; 12 专为老年人及残疾人使用的建筑,其乘客电梯应设置监 控系统, 梯门宜装可视窗,并应符合现行国家标准《无障碍设计 规范》GB 50763 的有关规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.9.2', '自动扶梯、自动人行道应符合下列规定: 1自动扶梯和自动人行道不应作为安全出口。 32 2 出入口畅通区的宽度从扶手带端部算起不应小于2.5m, 人员密集的公共场所其畅通区宽度不宜小于3.5m。 4 栏板应平整、光滑和无突出物;扶手带顶面距自动扶梯 前缘、自动人行道踏板面或胶带面的垂直高度不应小于0. 9m。 5 扶手带中心线与平行墙面或楼板开口边缘间的距离:当 相邻平行交叉设置时, 两梯(道)之间扶手带中心线的水平距离 不应小于0. 5m,否则应采取措施防止障碍物引起人员伤害。 6 自动扶梯的梯级、自动人行道的踏板或胶带上空,垂直 净高不应小于2.3m。 7 自动扶梯的倾斜角不宜超过 30^°, 额定速度不宜大于 0.75m/s; 当提升高度不超过6.0m, 倾斜角小于等于35°时, 额 定速度不宜大于0.5m/s;当自动扶梯速度大于0.65m/s时,在 其端部应有不小于1. 6m 的水平移动距离作为导向行程段。 8 倾斜式自动人行道的倾斜角不应超过12^°, 额定速度不 应大于0.75m/s。当踏板的宽度不大于1.1m, 并且在两端出人 口踏板或胶带进人梳齿板之前的水平距离不小于1.6m时,自动 人行道的最大额定速度可达到 0. 9m s。 10 设置自动扶梯或自动人行道所形成的上下层贯通空间, 应符合现行国家标准《建筑设计防火规范》GB 50016的有规定。 11 当自动扶梯或倾斜式自动人行道呈剪刀状相对布置时, 以及与楼板、梁开口部位侧边交错部位, 应在产生的锐角口前部 1.0m 范围内设置防夹、防剪的预警阻挡设施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.10', '墙身和变形缝', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.10.1', '墙身应根据其在建筑物中的位置、作用和受力状态确定 33 墙体厚度、材料及构造做法,材料的选择应因地制宜。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.10.2', '外墙应根据当地气候条件和建筑使用要求,采取保温、 隔热、隔声、防火、防水、防潮和防结露等措施,并应符合国家 现行相关标准的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.10.3', '墙身防潮、防渗及防水等应符合下列规定: 其迎水面一侧应设防水层;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.10.4', '在外墙的洞口、门窗等处应采取防止产生变形裂缝的加 固措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.10.5', '变形缝包括伸缩缝、沉降缝和抗震缝等,其设置应符合 下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11', '门 窗 6.11.1门窗选用应根据建筑所在地区的气候条件、节能要求等 34 因素综合确定, 并应符合国家现行建筑门窗产品标准的规定。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.2', '门窗的尺寸应符合模数,门窗的材料、功能和质量等应 满足使用要求。门窗的配件应与门窗主体相匹配,并应满足相应 技术要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.3', '门窗应满足抗风压、水密性、气密性等要求、且应综合 考虑安全、采光、节能、通风、防火、隔声等要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.4', '门窗与墙体应连接牢固,不同材料的门窗与墙体连接处 应采用相应的密封材料及构造做法。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.5', '有卫生要求或经常有人员居住、活动房间的外门窗宜设 置纱门、纱窗。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.6', '窗的设置应符合下列规定: 2 公共走道的窗扇开启时不得影响人员通行,其底面距走 道地面高度不应低于2. 0m; 3 公共建筑临空外窗的窗台距楼地面净高不得低于0. 8m, 否则应设置防护设施,防护设施的高度由地面起算不应低 于0.8m; 4 居住建筑临空外窗的窗台距楼地面净高不得低于0.9m, 否则应设置防护设施,防护设施的高度由地面起算不应低 于0.9m; 5 当防火墙上必须开设窗洞口时,应按现行国家标准《建 筑设计防火规范》GB 50016 执行。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.7', '当凸窗窗台高度低于或等于0.45m时,其防护高度从 窗台面起算不应低于0. 9m;当凸窗窗台高度高于0. 45m时.其 防护高度从窗台面起算不应低于0. 6m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.8', '天窗的设置应符合下列规定: 1天窗应采用防破碎伤人的透光材料: 2天窗应有防冷凝水产生或引泄冷凝水的措施。多雪地区 应考虑积雪对天窗的影响; 35', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.11.9', '门的设置应符合下列规定: 1门应开启方便、坚固耐用; 2手动开启的大门扇应有制动装置,推拉门应有防脱轨的 措施; 7门的开启不应跨越变形缝; 8 当设有门斗时,门扇同时开启时两道门的间距不应小于 0. 8m;当有无障碍要求时,应符合现行国家标准《无障得设计 规范》GB 50763 的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.12.1', '建筑幕墙应综合考虑建筑物所在地的地理、气候、环境 及使用功能、高度等因素, 合理选择幕墙的形式。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.12.2', '建筑幕墙应根据不同的面板材料,合理选择幕墙结构形 式、配套材料、构造方式等。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.12.3', '建筑幕墙应满足抗风压、水密性、气密性、保温、隔 热、隔声、防火、防雷、耐撞击、光学等性能要求,且应符合国 家现行有关标准的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.12.4', '建筑幕墙设置的防护设施应符合本标准第6.11.6 条的 规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.12.5', '建筑幕墙工程宜有安装清洗装置的条件。 6.13 楼地面', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.1', '地面的基本构造层宜为面层、垫层和地基;楼面的基本 36 构造层宜为面层和楼板。当地面或楼面的基本构造不能满足使用 或构造要求时,可增设结合层、隔离层、填充层、找平层、防水 层、防潮层和保温绝热层等其他构造层。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.2', '除有特殊使用要求外、楼地面应满足平整、耐磨、不起 尘、环保、防污染、隔声、易于清洁等要求,且应具有防滑 性能。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.3', '厕所、浴室、盥洗室等受水或非腐蚀性液体经常浸湿的 楼地面应采取防水、防滑的构造措施,并设排水坡坡向地漏。有 防水要求的楼地面应低于相邻楼地面 15.0mm。经常有水流淌的 楼地面应设置防水层,宜设门槛等挡水设施,且应有排水措施, 其楼地面应采用不吸水、易冲洗、防滑的面层材料、并应设置防 水隔离层。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.4', '建筑地面应根据需要采取防潮、防基土冻胀或膨胀、防 不均匀沉陷等措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.5', '存放食品、食料、种子或药物等的房间、其楼地面应采 用符合国家现行相关卫生环保标准的面层材料。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.6', '受较大荷载或有冲击力作用的楼地面,应根据使用性质 及场所选用由板、块材料、混凝土等组成的易于修复的刚性构 造, 或由粒料、灰土等组成的柔性构造。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13.7', '木板楼地面应根据使用要求及材质特性,采取防火、防 腐、防潮、防蛀、通风等相应措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14', '屋 面', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14.1', '屋面工程应根据建筑物的性质、重要程度及使用功能, 结合工程特点、气候条件等按不同等级进行防水设防,合理采取 保温、隔热措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14.2', '屋面排水坡度应根据屋顶结构形式、屋面基层类别、防 水构造形式、材料性能及当地气候等条件确定,且应符合 表6.14.2的规定,并应符合下列规定: 1 屋面采用结构找坡时不应小于3%,采用建筑找坡时不 37 应小于2%; 2 瓦屋面坡度大于100%以及大风和抗震设防烈度大于7 度的地区,应采取固定和防止瓦材滑落的措施; 3 卷材防水屋面檐沟、天沟纵向坡度不应小于1%、金属 屋面集水沟可无坡度; 4 当种植屋面的坡度大于20%时,应采取固定和防止滑落 的措施。 表6.14.2 屋面的排水坡度 屋面类别 屋面排水坡度(%) 平屋面 防水卷材屋面 ≥2、<5 块瓦 ≥30 瓦屋面 波形瓦 ≥20 沥青瓦 ≥20 金属屋面 压型金属板、金属夹芯板 单层防水卷材金属屋面 ≥5 ≥2 种植屋面 种植屋面 ≥2、<50 采光屋面 玻璃采光顶 ≥5', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14.3', '上人屋面应选用耐霉变、拉伸强度高的防水材料。防水 层应有保护层, 保护层宜采用块材或细石混凝土。', FALSE, '建议性条文')
;

INSERT INTO civil_building_articles (chapter_id, article_number, article_content, is_mandatory, article_type) VALUES
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14.4', '种植屋面结构应计算种植荷载作用.并宜设置植物浇灌 设施,防水层应满足耐根穿刺要求。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14.5', '屋面排水应符合下列规定: 38 当屋面采用虹吸式雨水排水系统时,应设溢流设施,集 水沟的平面尺寸应满足汇水要求和雨水斗的安装要求,集水沟宽 度不宜小于300mm,有效深度不宜小于250mm,集水沟分水线 处最小深度不应小于100mm;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.14.6', '屋面构造应符合下列规定: 1 设置保温隔热层的屋面应进行热工验算,应采取防结露、 防蒸汽渗透等技术措施,且应符合现行国家标准《建筑设计防火 规范》GB 50016 的相关规定; 5 屋面应设上人检修口;当屋面无楼梯通达。并低于10m 时,可设外墙爬梯,并应有安全防护和防止儿童攀爬的措施;大 型屋面及异形屋面的上屋面检修口宜多于2 个:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15', '吊 顶', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.1', '室外吊顶应根据建筑性质、高度及工程所在地的地理、 39 气候和环境等条件合理选择吊顶的材料及形式。吊顶构造应满足 安全、防火、抗震、抗风、耐候、防腐蚀等相关标准的要求。室 外吊顶应有抗风揭的加强措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.2', '室内吊顶应根据使用空间功能特点、高度、环境等条件 合理选择吊顶的材料及形式。吊顶构造应满足安全、防火、抗 震、防潮、防腐蚀、吸声等相关标准的要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.3', '室外吊顶与室内吊顶交界处应有保温或隔热措施,且应 符合国家现行建筑节能标准的相关规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.4', '吊顶与主体结构的吊挂应有安全构造措施,重物或有振 动等的设备应直接吊挂在建筑承重结构上,并应进行结构计算, 满足现行相关标准的要求;当吊杆长度大于1.5m时,宜设钢结 构支撑架或反支撑。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.5', '吊顶系统不得吊挂在吊顶内的设备管线或设施上。', FALSE, '禁止性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.6', '管线较多的吊项应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.7', '当吊顶内敷设有水管线时,应采取防止产生冷凝水的 措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.15.8', '潮湿房间或环境的吊顶,应采用防水或防潮材料和防 结露、滴水及排放冷凝水的措施;钢筋混凝土顶板宜采用现 浇板。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.16', '管道井、烟道和通风道', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.16.1', '管道井、烟道和通风道应用非燃烧体材料制作,且应分 别独立设置,不得共用。 40', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.16.2', '管道井的设置应符合下列规定: 3 管道井壁、检修门、管井开洞的封堵做法等应符合现行 国家标准《建筑设计防火规范》GB 50016 的有关规定。 4 管道并宜在每层临公共区域的一侧设检修门, 检修门门 槛或井内楼地面宜高出本层楼地面,且不应小于0. 1m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.16.3', '进风道、排风道和烟道的断面、形状、尺寸和内壁应有 利于进风、排风、排烟(气)通畅,防止产生阻滞、涡流、窜 烟、漏气和倒灌等现象。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.16.4', '自然排放的烟道和排风道宜伸出屋面,同时应避开门窗 和进风口。伸出高度应有利于烟气扩散,并应根据屋面形式、排 出口周围遮挡物的高度、距离和积雪深度确定, 伸出平屋面的高 度不得小于0. 6m。伸出坡屋面的高度应符合下列规定: 1 当烟道或排风道中心线距屋脊的水平面投影距离小于 1.5m时,应高出屋脊0.6m; 2 当烟道或排风道中心线距屋脊的水平面投影距离为1.5m~ 3.0m时,应高于屋脊,且伸出屋面高度不得小于0.6m; 3 当烟道或排风道中心线距屋脊的水平面投影距离大于 3. 0m时,可适当低于屋脊, 但其顶部与屋脊的连线同水平线之 间的夹角不应大于 10^° , 且伸出屋面高度不得小于0. 6m。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.16.5', '烟道和排风道的设置尚应符合国家现行相关标准的 规定。 41', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.17', '室内外装修', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.17.1', '室内外装修设计应符合下列规定: 2 装修工程应根据使用功能等要求,采用节能、环保型装 修材料,且应符合现行国家标准《建筑设计防火规范》GB 50016 的相关规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.172', '室内装修设计应符合下列规定: 3 室内装修材料应符合现行国家标准《民用建筑工程室内 环境污染控制规范》GB 50325 的相关要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.17.3', '外墙装修材料或构件与主体结构的连接必须安全牢固。 42 7室内环境', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.1', '光环境 7..1 建筑中主要功能房间的采光计算应符合现行国家标准 《建筑采光设计标准》GB 50033 的规定。 7..2 居住建筑的卧室和起居室(厅)、医疗建筑的一般病房的 采光不应低于采光等级|V级的采光系数标准值, 教育建筑的普通 教室的采光不应低于采光等级III级的采光系数标准值,且应进行 采光计算。采光应符合下列规定: 1每套住宅至少应有一个居住空间满足采光系数标准要求, 当一套住宅中居住空间总数超过4个时,其中应有2个及以上满 足采光系数标准要求; 2 老年人居住建筑和幼儿园的主要功能房间应有不小于 75%的面积满足采光系数标准要求。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.1.3', '有效采光窗面积计算应符合下列规定: 1 侧面采光时,民用建筑采光口离地面高度0.75m以下的 部分不应计人有效采光面积;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.1.4', '建筑照明的数量和质量指标应符合现行国家标准《建筑 照明设计标准》GB 50034 的规定。各场所的照明评价指标应符 合表7.1.4的规定。 表7.1.4 各场所的照明评价指标 建筑类型 评价指标 居住建筑 照度、显色指数 通用房间或场所 公共建筑 照度、照度均匀度、统 -眩光值、显色指数 43 续表7.1.4 建筑类型 评价指标 博物馆建筑 照度、照度均匀度、统一眩光值、显色指数、年曝光量 体育建筑 数、色温 水平照度、垂直照度、照度均匀度、眩光指数、显色指', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.1', '建筑物应根据使用功能和室内环境要求设置与室外空气 直接流通的外窗或洞口;当不能设置外窗和洞口时,应另设置通 风设施。 1 生活、工作的房间的通风开口有效面积不应小于该房间 地面面积的 1/20; 2 厨房的通风开口有效面积不应小于该房间地板面积的 1/10,并不得小于 \(0.6 ~m^{2}\) ; 7 2.3 严寒地区居住建筑中的厨房、厕所、卫生间应设自然通 风道或通风换气设施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.4', '厨房、卫生间的门的下方应设进风固定百叶或留进风 缝隙。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.5', '自然通风道或通风换气装置的位置不应设于门附近。 72.6 无外窗的浴室、厕所、卫生间应设机械通风换气设施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.7', '建筑内的公共卫生间宜设置机械排风系统。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3', '热湿环境', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3.1', '需要夏季防热的建筑物应符合下列规定: 44 《民用建筑热工设计规范》GB 50176和国家现行相关节能标准的 规定;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3.2', '设置空气调节的建筑物应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3.3', '需要冬季保温的建筑应符合下列规定: 3 围护结构应采取保温措施,保温设计应符合现行国家标 准《民用建筑热工设计规范》GB 50176和国家现行相关节能标 准的规定;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3.4', '冬季日照时数多的地区,建筑宜设置被动式太阳能利用 措施。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3.5', '夏热冬冷地区的长江中、下游地区和夏热冬暖地区建筑 的室内地面应采取防泛潮措施。 .3.6 供暖建筑应按照现行国家标准《民用建筑热工设计规范》 GB 50176 采取建筑物防潮措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.4', '声 环境', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.4.1', '民用建筑各类主要功能房间的室内允许噪声级、围护结 构(外墙、隔墙、楼板和门窗) 的空气声隔声标准以及楼板的撞 击声隔声标准,应符合现行国家标准《民用建筑隔声设计规范》 45 GB 50118 的规定。 7. 4.2 民用建筑的隔声减噪设计应符合下列规定: 7. 4.3 民用建筑内的建筑设备隔振降噪设计应符合下列规定: 1民用建筑内产生噪声与振动的建筑设备宜选用低噪声产 品, 且应设置在对噪声敏感房间干扰较小的位置。当产生噪声与 振动的建筑设备可能对噪声敏感房间产生噪声干扰时,应采取有 效的隔振、隔声措施。 2与产生噪声与振动的建筑设备相连接的各类管道应采取 软管连接、设置弹性支吊架等措施控制振动和固体噪声沿管道传 播。并应采取控制流速、设置消声器等综合措施降低随管道传播 的机械辐射噪声和气流再生噪声。 3 当各类管道穿越噪声敏感房间的墙体和楼板时,孔洞周 边应采取密封隔声措施;当在噪声敏感房间内的墙体上设置嵌人 墙内对墙体隔声性能有显著降低的配套构件时,不得背对背布 置,应相互错开位置,并应对所开的洞(槽)采取有效的隔声封 堵措施。 46', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.4.4', '柴油发电机房应采取机组消声及机房隔声综合治理措施。 冷冻机房、换热站泵房、水泵房应有隔振防噪措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.4.5', '音乐厅、剧院、电影院、多用途厅堂、体育场馆、航站 楼及各类交通客运站等有特殊声学要求的重要建筑, 宜根据功能 定位和使用要求,进行建筑声学和扩声系统专项设计。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.4.6', '人员密集的室内场所,应进行减噪设计。 47', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1', '给水排水', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.1', '建筑给水设计应符合下列规定: 8..2 生活饮用水水池(箱)、供水泵房等设置应符合下列 规定: 1建筑物内的生活饮用水水池(箱)体应采用独立结构形 式,不得利用建筑物的本体结构作为水池(箱)的壁板、底板及 顶盖;与其他用水水池 (箱) 并列设置时,应有各自独立的分 隔墙; 2 埋地生活饮用水贮水池周围 10.0m以内,不得有化粪 池、污水处理构筑物、渗水井、垃圾堆放点等污染源,周围 2. 0m以内不得有污水管和污染物; 6生活给水泵房内的环境应满足国家现行有关卫生标准的 要求。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.3', '生活热水的热源应遵循国家或地方有关规定利用太阳能, 新建建筑太阳能集热器的设置必须与建筑设计一体化。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.4', '当采用同层排水时,卫生间的地坪和结构楼板均应采取 48 可靠的防水措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.5', '给水排水管道敷设应符合下列规定: 1 给水排水管道不应穿过变配电房、电梯机房、智能化系 统机房、音像库房等遇水会损坏设备和引发事故的房间,以及博 物馆类建筑的藏品库房、档案馆类建筑的档案库区、图书馆类建 筑的书库等; 并应避免在生产设备、遇水会引起爆炸燃烧的原料 和产品、配电柜上方通过;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.6', '化粪池距离地下取水构筑物不得小于30.0m。化粪池池 外壁距建筑物外墙不宜小于5. 0m, 并不得影响建筑物基础。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.7', '污水处理站、中水处理站的设置应符合下列规定: 1 建筑小区污水处理站、中水处理站宜布置在基地主导风 向的下风向处,且宜在地下独立设置。以生活污水为原水的地面 处理站与公共建筑和住宅的距离不宜小于15.0m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.8', '室内消火栓应设置在明显易于取用及便于火灾扑救的位 置。消火栓箱暗装在防火墙或承重墙上时,应采取不能减弱本墙 体耐火等级的技术措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.9', '消防水池的设计应符合下列规定: 49 2 消防用水等非生活饮用水水池的池体宜根据结构要求与 建筑物本体结构脱开, 采用独立结构形式。钢筋混凝土水池,其 池壁、底板及顶板应做防水处理, 且内表面应光滑易于清洗。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.10', '消防水泵房设置应符合下列规定: 1不应设置在地下3 层及以下,或室内地面与室外出入口 地坪高差大于10.0m 的地下楼层;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.11', '高位消防水箱设置应符合下列规定: 1水箱最低有效水位应高于其所服务的水灭火设施;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.12', '设置气体灭火系统的房间应符合下列规定: 1 围护结构及门窗的耐火极限不宜低于0.5h,吊顶的耐火 极限不宜低于0. 25h; 2 围护结构及门窗的允许压强不宜小于1.2kPa; 3 围护结构上应设置泄压口,泄压口应开向室外或公共走 道, 泄压口下沿应位于房间净高 2/3以上的位置,泄压口面积应 经计算确定; 4门应向疏散方向开启,并应能自动关闭。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.13', '冷却塔位置的选择应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.14', '燃油(气) 热水机组机房的布置应符合下列规定: 1机房宜与其他建筑物分离独立设置。当设在建筑物内时。 不应设置在人员密集场所的上、下层或贴邻部位,应布置在靠外 50 墙部位, 其疏散门应直通安全出口。在外墙开口部位的上方,应 设置宽度不小于1.0m 的不燃烧体防火挑檐。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2', '暖通空调 8. 2.1 设有供暖系统的民用建筑应符合下列规定:', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.22', '设有机械通风系统的民用建筑应符合下列规定: 1 新风采集口应设置在室外空气清新、洁净的位置或地点; 废气及室外设备的出风口应高于人员经常停留或通行的高度;有 毒、有害气体应经处理达标后向室外高空排放;与地下供暖管 沟、地下室开敞空间或室外相通的共用通风道底部,应设有防止 小动物进入的篦网; 4事故排风系统的室外排风口不应布置在人员经常停留或 51 通行的地点以及邻近窗口、天窗、出入口等位置;且排风口与进 风口的水平距离不应小于 20. 0m, 否则宜高出 6.0m以上;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.23', '设有空气调节系统的民用建筑应符合下列规定: 4 空调管道的热膨胀、暗装设备检修等应分别符合本标准 第8.2.1条、第8.2.2条的相关规定;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2.4', '既有建筑加装暖通空调设备不得危害结构安全,室外设 备不应危及邻居或行人。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2.5', '冷热源站房的设置应符合下列规定: 2主机房宜采用水泥地面,主机基座周边宜设排水明沟; 4多台主机联合运行的站房应设置集中控制室,控制室应 采用隔声门,锅炉房控制室应采用具有抗爆能力且固定的观 察窗。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2.6', '燃油(燃气) 锅炉或设备用房应设在便于燃料储存及输 52 配、且能与室外保持足够通风量的位置,不应靠近或危及人员密 集的空间,且人员逃生、泄爆、排水、排汽等防护措施应符合现 行国家标准《锅炉房设计规范》GB 50041和《建筑设计防火规 范》GB 50016 的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.1', '民用建筑物内设置的变电所应符合下列规定: 1) 宜接近用电负荷中心; 2) 应方便进出线; 3) 应方便设备吊装运输; 4)不应在厕所、卫生间、盥洗室、浴室、厨房或其他蓄 水、经常积水场所的直接下一层设置,且不宜与上述 场所相贴邻,当贴邻设置时应采取防水措施; 5) 变压器室、高压配电室、电容器室,不应在教室、居 室的直接上、下层及贴邻处设置;当变电所的直接上、 下层及贴邻处设置病房、客房、办公室、智能化系统 机房时,应采取屏蔽、降噪等措施。 2 地上高压配电室宜设不能开启的自然采光窗,其窗距室 外地坪不宜低于1. 8m; 地上低压配电室可设能开启的不临街的 自然采光通风窗,其窗应按本条第7款做防护措施。 3 变电所宜设在一个防火分区内。当在一个防火分区内设 置的变电所,建筑面积不大于 \(200.0 ~m^{2}\) 时,至少应设置1个直接 通向疏散走道(安全出口) 或室外的疏散门;当建筑面积大于 \(200.0 ~m^{2}\) 时,至少应设置2个直接通向疏散走道(安全出口)或 室外的疏散门;当变电所长度大于60.0m时,至少应设置3个 直接通向疏散走道(安全出口)或室外的疏散门。 5 当变电所设置2个及以上疏散门时,疏散门之间的距离 53 不应小于5.0m,且不应大于 40.0m。 6 变压器室、配电室、电容器室的出人口门应向外开启。 同一个防火分区内的变电所,其内部相通的门应为不燃材料制作 的双向弹簧门。当变压器室、配电室、电容器室长度大于 7. 0m 时,至少应设2个出入口门。 8 变电所地面或门槛宜高出所在楼层楼地面不小于0.1m。 如果设在地下层,其地面或门槛宜高出所在楼层楼地面不小于 0.15m。变电所的电缆夹层、电缆沟和电缆室应采取防水、排水 措施。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.2', '变电所防火门的级别应符合下列规定:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.3', '柴油发电机房应符合下列规定: 1 柴油发电机房的设置应符合本标准第8.3.1 条的规定。 3 当发电机间、控制及配电室长度大于7.0m时,至少应 设2个出入口门。其中一个门及通道的大小应满足运输机组的需 要,否则应预留运输条件。 54 室外。室外排烟管(井)的口部下缘距地面高度不宜小于2.0m。 8 建筑物内设或外设储油设施设置应符合现行国家标准 《建筑设计防火规范》GB 50016的规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.4', '智能化系统机房应符合下列规定: 1机房地面或门槛宜高出本层楼地面不小于0. 1m。 2机房宜铺设架空地板、网络地板或地面线槽.宜采用防 静电、防尘材料,机房净高不宜小于2.5m。 4消防控制室、安防监控中心的设置应符合有关国家现行 消防、安防标准的规定。消防控制室、安防监控中心宜设在建筑 物的首层或地下一层。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.5', '电气坚井的设置应符合下列规定: 2 250.0m 及以上的超高层建筑应设2个及以上强电坚井, 宜设2个及以上弱电坚井。 4设有综合布线机柜的弱电竖井宜大于 \(5. 0 ~m^{2}\) :采用对绞 电缆布线时,其距最远端信息点的布线距离不宜大于90. 0m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.6', '线路敷设应符合下列规定: 55 进人时应做好防护措施。 3 在楼板、墙体、柱内暗敷的电气线缆保护管其覆盖层不 应小于15.0mm; 在楼板、墙体、柱内暗敷的消防设备配电线缆 保护管其覆盖层不应小于30. 0mm。覆盖层应采用不燃性材料。 4 电缆桥架顶距楼板不宜小于0. 3m, 距梁底不宜小于0. Im。 83.7 建筑物防雷接闪器的设置应符合现行国家标准《建筑物 防雷设计规范》GB 50057 的规定.并应符合下列规定: 2 除第1款之外的建筑物,当屋顶钢筋网以上的防水层和 混凝土层需要保护时,屋顶层应采用明敷接闪网等接闪器: 3 除第1款之外的建筑物,当周围有人员停留时,其女儿 墙或檐口应采用明敷接闪带等接闪器。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4', '燃 气', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.1', '室外燃气管道宜埋地敷设,并应符合下列规定: 1不得从建筑物和大型构筑物(不含架空建筑物和构筑物) 的下面穿过; 2 不应穿过电力、电缆、供热和污水等地下管沟或同沟敷 设,与建(构) 筑物或相邻管道之间的水平和垂直净距、覆土深 度等应符合现行国家标准《城镇燃气设计规范》GB 50028的有 关规定。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.2', '燃气管道采用室外架空敷设时,应符合下列规定: 1可沿建筑物外墙或屋面敷设: 2 中压燃气管道,可沿耐火等级不低于二级的居住建筑或 公共建筑的外墙敷设,该建筑外墙的耐火极限不得低于2.5h; 56 口的水平净距,中压管道不宜小于0.5m, 低压管道不宜小 于0.3m。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.3', '区域燃气调压站(箱)可设置于地上或地下,与建筑物 的水平净距应符合现行国家标准《城镇燃气设计规范》GB 50028 的有关规定。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.4', '楼栋调压箱或专用调压装置可悬挂在耐火等级不低于二 级的居住建筑的外墙上,外墙体的耐火极限不得小于2.5h。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.5', '当调压装置进口压力不大于0.4 MPa, 且调压器进出口 管径不大于DN100时,可设置在用气建筑物的平屋顶上,并应 符合下列规定: 2 调压箱(或露天调压装置) 与建筑物烟囱的水平净距不 应小于5.0m。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.6', '燃气表、用户调压器的设置, 应符合下列规定: 4不应设置在有电源、电器开关及其他电气设备的管道 井内。', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.7', '液化石油气和相对密度大于0.75 的燃气调压计量装置及 管道、燃具、用气设备等设施不得设于地下室、半地下室等地下 空间。', FALSE, '禁止性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.8', '当采用液化石油气瓶组自然气化。总容积小于等于 \(1. 0 ~m^{3}\) 时, 瓶组间可设置在与建筑物(高层建筑、重要公共建筑 和居住建筑除外)外墙毗连的单层专用房间内,单层专用房间应 符合下列规定: 57 4 室温不应高于15°C,且不应低于0°C;', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.9', '当瓶组气化站配置气瓶的总容积超过 \(1. 0 ~m^{3}\) 或采用强制 气化时。应独立设置在高度不低于2. 2m 的专用房间内。专用房 间与其他建(构)筑物的防火间距应符合国家现行相关标准的 规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.10', '商业和公共建筑用户使用的气瓶组严禁与燃具布置在同 一房间内。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.11', '在室内设置的燃气管道和阀门应符合下列规定: 4不得设置在人防工程和避难场所,以及非用燃气的人员 密集场所:', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.12', '燃气管道宜明设。当暗埋和暗封燃气管道时。应符合现 行国家标准《城镇燃气技术规范》GB 50494和《城镇燃气设计 规范》GB 50028 的有关规定。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.13', '燃气管道坚井应符合下列规定: 58 1竖井的底部和顶部应直接与大气相通; 2 管道竖井的墙体应为耐火极限不低于1.0h的不燃烧体, 井壁上的检查门应采用丙级防火门。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.14', '居住建筑使用燃具的厨房或设备间应符合下列规定: 1 净高度不应低于2. 2m, 并应有良好的自然通风;', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.15', '居住建筑的燃具燃烧烟气宜通过坚向烟道排至室外, 且 不得与使用固体燃料的设备共用一套排烟设施。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.16', '高层民用建筑内使用燃气应采用管道供气。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.17', '公共建筑中燃具的设置应符合下列规定: 1) 正常工作时,换气次数不应小于6 次/h;事故通风时, 换气次数不应小于12次/h;不工作时,换气次数不应 小于3次/h; 2) 当燃烧所需的空气由室内吸取时。应满足燃烧所需的 空气量。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.4.18', '公共建筑燃气直燃机、燃气锅炉等大型燃气用气设备的 排烟应符合下列规定: 59 本标准用词说明 1) 表示很严格,非这样做不可的: 正面词采用"必须".反面词采用"严禁"; 2) 表示严格,在正常情况下均应这样做的: 正面词采用"应",反面词采用"不应"或"不得"; 3) 表示允许稍有选择,在条件许可时首先应这样做的: 正面词采用"宜",反面词采用"不宜"; 4) 表示有选择,在一定条件下可以这样做的,采用 "可"。 60 引用标准名录 1《建筑模数协调标准》GB/T 50002 2《建筑结构荷载规范》GB 50009 3《建筑设计防火规范》GB 50016 4《城镇燃气设计规范》GB 50028 5 《建筑采光设计标准》(GB 50033 6《建筑照明设计标准》GB 50034 7《锅炉房设计规范》GB 50041 8《建筑物防雷设计规范》GB 50057 9《建筑结构可靠性设计统一标准》GB 50068 10 《住宅设计规范》GB 50096 11《地下工程防水技术规范》GB 50108 12《民用建筑隔声设计规范》GB 50118 13《民用建筑热工设计规范》GB 50176 14《民用建筑工程室内环境污染控制规范》GB 50325 15 《城镇燃气技术规范》GB 50494 16《无障碍设计规范》GB 50763 17《车库建筑设计规范》JGJ100 61 中华人民共和国国家标准 民用建筑设计统一标准 GB 50352-2019 条文说明 编制说明 《民用建筑设计统一标准》GB 50352-2019,经住房和城 乡建设部2019年3月13日以第57号公告批准、发布。 本标准是在《民用建筑设计通则》GB 50352-2005的基础 上修订而成的,上 版的主编单位是中国建筑设计研究院、中国 建筑标准设计研究院,参编单位是中国城市规划设计研究院、中 国建筑科学研究院、中国建筑西南设计研究院、中国建筑西北设 计研究院、中南建筑设计院、北京市建筑设计研究院、上海市建 筑设计研究院有限公司、甘肃省建筑设计研究院、清华大学建筑 设计研究院、同济大学建筑设计研究院、广东省建筑科学研究 院、广州市城市规划勘测设计研究院、重庆大学建筑城规学院、 哈尔滨工.业大学建筑学院。主要起草人员是赵冠谦、崔恺、张 华、顾均、张树君、叶茂煦、朱昌廉、李桂文、郑国英、陈华 宁、耿长孚、涂英时、章竞屋、李耀培、潘忠诚、袁奇峰、林若 慈、赵元超、桂学文、方稚影、丁再励、王为、孙兰、杜志杰、 张播、孙彤。 本标准在编制过程中, 编制组进行了广泛的调查研究, 认真 总结工程实践经验,参考有关国内标准和国外先进标准,并在广 泛征求意见的基础上,对主要问题进行了反复讨论、协调,最终 确定各项技术要求。 为便于广大设计、施工、科研、学校等单位有关人员在使用 本标准时能正确理解和执行条文规定。《民用建筑设计统一标准》 编制组按章、节、条顺序编制了本标准的条文说明、对条文规定 的目的、依据以及执行中需注意的有关事项进行了说明,还着重 64 对强制性条文的强制性理由做了解释。但是。本条文说明不具备 与标准正文同等的法律效力,仅供使用者作为理解和把握标准规 定的参考。 65 目次 1 总则...68 3 基本规定...70', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.1.2', '民用建筑高度和层数的分类主要是按照现行国家标准 《建筑设计防火规范》GB 50016和《城市居住区规划设计标准》 GB 50180来划分的。当建筑高度是按照防火标准分类时,其计 算方法按现行国家标准《建筑设计防火规范》GB 50016执行。 一般建筑按层数划分时,公共建筑和宿舍建筑1~3层为低层, 4~6层为多层,大于等于7层为高层;住宅建筑1~3层为低层, 4~9层为多层,10层及以上为高层。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '3'), '3.4', '建筑与环境 环境即包括以大气、水、土壤、植物、动物、微生物等为内 容的物质因素,也包括以观念、制度、行为准则等为内容的非物 质因素;既包括自然因素, 也包括人文因素:既包括非生命体形 式,也包括生命体形式。环境是相对于某个主体而言的,主体不 同, 环境的大小、内容等也就不同。狭义的环境。如环境问题中 的"环境"一词, 往往指向对于人类这个主体而言的一切自然环 71 境要素的总和。 建筑设计需考虑的环境包含自然环境与人文环境(包含了社 会、文化、宗教等因素)。建筑应承担技术的环境责任与空间的 社会责任。建筑与环境的关系应以"人与自然共牛"、"人与社会 共生" 为基本出发点,贯彻可持续发展的战略,树立"人一建 筑一环境"和谐发展的意识,从环境角度关注建筑全寿命期的过 程;实现建筑与自然的永续发展、建筑与社会的和谐共生。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.2.2', '本条阐明了建筑基地 高程设计的基本原则。建筑 基地地面高程设计应依据所 在城市或镇详细规划(包括 控制性详细规划或修建性详 细规划) 的高程控制要求进 行场地设计,并处理好建筑 基地雨水的排放问题。一方 面,高程设计应充分考虑建 筑与场地以及建筑基地与相邻建筑基地的关系,不应产生内涝; 另一方面, 高程设计应综合考虑雨水的收集回用,有利于调蓄雨 水, 合理控制雨水外排。海绵城市建设强调从源头做起,合理控 制每个建设单元的雨水径流,并不是一概外排。也就是说, 场地 设计时应充分结合原有自然条件, 因地制宜地设计场地控制点高 程、设置绿色雨水设施(如结合场地相对低洼处设计汗塘、下凹 式绿地等), 既可起到调蓄雨水、减少和净化雨水径流的作用, 也可在雨水过多时再外排以保障场地不产生内涝。因此,建筑基 地的高程设计应结合地面水的收集与排放统筹设计。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.2.3', '本条明确了为避免相邻建筑基地因建筑物紧贴用地边界 建造而造成各种有碍安全、卫生等后患和民事纠纷应遵守的基本 规定,以保障建筑物之间的防火间距、消防通道以及通风、采光 和日照等建设要求。 1明确了建筑物应布局在建筑控制线内。通常在控制性详 细规划图则中, 出于对区域整体空间的统筹以及安全、卫生的考 虑会标定建设用地地块(建筑基地) 的建筑控制线(如建筑后退 红线、建筑后退线等,或因建筑界面连续性需求有时会有建筑贴 线率等控制要求)以限定建筑的建造范围, 建筑设计应满足这些 规划控制要求。 2没有明确划定建筑控制线的建筑基地,建筑物与相邻建 筑基地之间关系的规定应满足建筑防火等要求。 76 3 明确规定了邻接建筑基地中两栋建筑物(如住宅、商店 等建筑)毗连建造的条件, 必须满足现行国家标准《建筑设计防 火规范》GB 50016 的有关规定。如图4所示:(1)两栋建筑各 自前后皆留有符合防火通道宽度要求的空地或道路;(2)两栋建 筑之间设置了防火墙。 后 基地边界 空地或道路 建筑 建筑 空地或道路 前 基地边界 图4 相邻建筑基地建筑毗连建造示意 4 是为了保障建筑基地和相邻建筑基地内有日照要求的建 筑或场地的合法权益的基本规定。我国现行国家标准、行业标准 及地方标准,分别对住宅、老年人居住建筑、宿舍以及中小学 校、幼儿园、托儿所、医院等建筑的部分用房规定了相应的日照 标准, 建筑设计应满足相关标准的规定;对于体形比较复杂的建 筑和高层建筑,宜进行日照分析,并应将建筑基地及周围建筑基 地已建、在建和拟建建筑的影响考虑在内。对于城市更新项目, "不得降低"日照标准分为两种情况:周边既有建筑物改造前满 足日照标准的,应保证其改造后仍符合相关日照标准的要求;周 边既有建筑物改造前未满足日照标准的,改造后不可再降低其原 有的日照水平。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '4'), '4.4.3', '地下建筑连接体分廊道连接和地下室整体开发连接两大 类,在其上部的覆土深度,均须满足市政各类管道等设施敷设的 要求,同时为日后市政管线扩容或地铁通行提供可能。 建筑连接体的设计还应满足现行行业标准《城市人行天桥与 人行地道技术规范》CJJ 69 的相关技术要求。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.1.2', '本条各款重点强调建筑间距应满足防火、城市规划、采 光、日照等场地设计的要求。 2 天然采光也有建筑间距要求。由于各地所处光气候区等 情况不同难以作出间距具体数据。原则是天然光源应满足各建筑 采光系数标准值之规定,具体计算在本标准第7.1节条文和条文 说明及现行国家标准《建筑采光设计标准》GB 50033中已有规 定。无论是相邻地建筑,或同一基地内建筑之间都不应挡住建筑 用房的采光。建筑和场地日照标准在现行国家标准《城市居住区 规划设计标准》GB 50180中有明确规定、住宅、宿舍、托儿所、 幼儿园、宿舍、老年人居住建筑、医院病房楼等类型建筑也有相 关日照标准,并应执行当地城市规划行政主管部门依照目照标准 制定的相关规定。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.2.5', '本条对室外停车场作出规定,包括机动车和非机动车停 车场,这类停车场一般在体育场馆、剧场和展览馆等大型观演、 展览建筑中较为多见。停车场的坡度下限是为了满足径流排水, 停车场出入口宜分离设置,当出入口位于单向道路一侧时,应沿 道路行车方向先设置进口、后设置出口;当出入口位于双向行驶 84 道路一侧时,应采取右转进出的方式布置,以避免进、出车辆交 叉。无障碍机动车停车位数量应符合现行国家标准《无障碍设计 规范》GB 50763 的要求,应注意无障碍机动车停车位数与建设 内容有关,城市广场、城市绿地、居住区、公共建筑对无障碍停 车数的要求是有区别的(表1)。停车位要求有乔木遮阳是为了 体现绿色、生态的室外环境要求,是降低夏季车内的温度, 减少 油耗和二氧化碳的排放的有效措施。 表1无障碍停车位数量要求 类 型 <50辆 50~100辆 停车位数量 >100辆 城市广场 ≥1个 ≥2个 ≥总停车数的2% 城市绿地 ≥1个 ≥2个 ≥总停车数的 2% 公共建筑 ≥1个 ≥总停车数的1% 居住区 ≥总停车数的0.5%, 若设有多个停车场,每处 ≥1个', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '52'), '52.6', '本条为新增内容,对停车场出入口数量作出规定。虽然 大部分建筑均通过设置地下停车库解决机动车停车问题,但对于 大型公共建筑尤其是文化、医疗、体育等建筑,室外停车场是不 可缺少的,有必要增加相关规定。本条参照了建设标准《城市公 共停车场工程项目建设标准》建标128-2010和行业标准《城市 道路工程设计规范》CJJ37 -2012 (2016年版),根据停车场的 分类对停车场出入口的数量及单、双向行驶的出入口作出规定, 既考虑停车场出入口的通行要求,也须考虑管理的方便。表2是 《城市公共停车场T程项目建设标准》建标128-2010规定的城 市公共停车场规模分类。 表2 城市公共停车场规模分类 停车场类型 停车位数量(个) 特大型停车场 >500 大型停车场 301~500 中型停车场 51~300 小型停车场 ≤50 85', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.4', '绿 化', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '5'), '5.5.9', '此条款的增加是为了维修方便和使用安全。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.2', '平面布置', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '6'), '6.13', '楼 地面', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.1.1', '居住建筑的功能房间包括卧室、起居室(厅)、书房、厨 房和卫生间。对于公共建筑,除走廊、核心筒、卫生间、电梯 间、机房等,其余的为功能房间。建筑采光按现行国家标准《建 筑采光设计标准》GB 50033 规定的采光等级进行验算。在建筑 方案设计阶段,其采光窗洞口面积和采光有效进深可按现行国家 标准《建筑采光设计标准》GB 50033 的规定进行估算。建筑采 光的评价指标为采光系数,在一般情况下,可利用现行国家标准 《建筑采光设计标准》GB 50033 提供的图表法确定标准规定的平 均采光系数或窗地面积比,对于大型公共建筑, 由于体形复杂, 窗户的形式和位置各异, 计算工作量大, 当需要对其进行采光分 析时,可使用软件来计算完成。', FALSE, '表格'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.1.2', '在现行国家标准《建筑采光设计标准》GB 50033中将住 宅建筑的卧室和起居室(斤)、医疗建筑的一般病房、教育建筑 的普通教室的采光系数标准值规定为强制性条文。 本条一般病房指人院病人接受观察、护理、治疗的用房,也 称病房,不包括隔离病房和监护病房。普通教室指按照班级标准 人数规模设置的、进行教学用的教室,不包括专用教室如实验 室、多媒体教室、美术教室、音乐教室、体育用房等。 本条规定的采光系数标准值一般需要利用采光软件进行模拟 计算, 因为目前住宅形式多样化,室外遮挡严重,外立面上形成 的各种自遮挡也会对采光产生不利影响。计算机模拟计算可以通 过严格建模, 精确计算, 定量给出平均采光系数和室内任一点的 采光系数值。 109 日照有朝向问题,会出现无日照的房间,而采光则不然,居住空 间都能获得采光,所以采光和日照标准不能完全等同, 应该有更 多的房间满足采光标准要求。居住空间的采光按套规定比较合 理, 鉴于我国现有住宅建筑类型多样, 特别是保障性住房,用地 一般比较紧张,至少也应该有一个居住空间满足采光系数标准, 其他居住空间可适当降低采光系数标准。对于一套住宅中居住空 间总数超过4个时,因有凹槽窗、凹阳台、封闭阳台、建筑遮挡 等也不可能全部满足采光标准要求,所以规定2个以上满足采光 系数标准。 2 老年人居住建筑指专为老年人设计、供其起居生活使用, 符合老年人生理、心理要求的居住建筑,其主要功能房间指卧 室、起居室(厅)。幼儿园的主要功能房间与公共建筑主要功能 房间的含义相同。本款老年人居住建筑、幼儿园的采光是按整栋 建筑考虑的,以上建筑应该比普通住宅要求更高,设计时选择的 环境条件也会更好,一般不会设计成凹槽窗、凹阳台, 阳台也不 一定做成封闭型的, 采光更容易满足,幼儿园参照了国家标准 《绿色建筑评价标准》GB/T 50378-2014第 8.2.6 条公共建筑主 要功能房间满足采光标准的面积比例,取其中间值 75%。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.2', '人员经常生活、休息、工作活动的空间(如居室、厨房、 儿童活动室、中小学生教室、学生公寓宿舍、育婴室、养老院、 111 病房等) 应采用直接自然通风。本条中规定的通风口面积的最低 限值保持了原《通则》的规定。进出风开口的有效面积应进行计 算,计算时将开启扇开到最大通风位置,然后计算有效通风 面积。 除了保证必需的通风开口面积,良好的通风效果还依赖是否 有通风路径。设计中应合理设置进出风口的平面位置、高度等, 以利于室内形成良好自然通风流场。 设置在外墙上的悬开窗,其通风开口有效面积按下列要求 确定: 1 当开启扇开启角度大于70°时,其面积可按窗的面积 计算。 2 当开启角度小于70°时,其面积可以按照下式计算: \[F_{p}=d(h+B) (1)\] 式中: \(F_{p}\) --通风开口有效面积 \((m^{2})\) ; d --开启扇顶(或底边) 到其关闭位置的距离(m); h --开启洞口净高(m); B --开启洞口的净宽 (m)。', FALSE, '一般性条文')
;

INSERT INTO civil_building_articles (chapter_id, article_number, article_content, is_mandatory, article_type) VALUES
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.3', '严寒地区的建筑冬季均需采暖。采暖期间建筑物各用房 的外窗、外门都要关闭。一方面是冬季室内污染相当严重,另一 方面又不能开窗换气造成热量损失。因此,要求严寒地区的居住 用房、厨房、卫生间应设置竖向或水平向自然通风道或通风换气 设施(如窗式通风装置等)。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.2.6', '为了避免浴室、厕所、卫生间中的污浊空气影响周围房 112 间的空气质量, 无外窗的浴室、卫生间等房间应设置机械通风换 气设施,且门的下方应设进风固定百叶或留进风缝隙。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '73'), '73.1', '建筑的夏季防热应实施综合防治,这里主要指以下几 方面: 通过绿化、水体等改善室外的热湿环境。建筑绿化是行之有 效的防热措施,可以在建筑物的东、西向墙面种植可攀爬的植 物,通过坚向绿化吸热减少太阳辐射热传入室内。也可以在建筑 物的屋顶上种植绿化,设置棚架廊亭,建水池、喷泉等以降温、 调节小气候。 屋面及东、西墙面是太阳辐射强度最高的表面,遮阳更加重 要,所以必须采取遮阳措施。在建筑受太阳辐射作用的主要朝向 设置遮阳装置。遮阳装置优先采用活动外遮阳;当选用固定建筑 遮阳时,东、西向外窗应设置组合遮阳。采光顶是透光的屋顶, 采光顶往往高于其他屋面, 热气容易聚集,在采光顶或其周边设 置通风设施,可高效地排除室内热量,利于组织自然通风。 建筑的屋顶和东、西墙隔热必须满足现行国家标准《民用建 筑热工设计规范》GB 50176 的要求;宜采用绿化屋面或反射隔 热屋面进行屋面隔热,东、西墙宜采用反射隔热墙体。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.3.6', '当建筑围护结构的温度低于空气露点温度时,水蒸气析 出形成液态水。一方面,受潮的建筑在冻融循环的作用下易于破 坏; 另一方面, 潮湿为细菌提供了滋生的环境, 霉变破坏粉刷 层,影响美观和健康。 供暖建筑冬季防潮设计包括围护结构内部冷凝和内表面结露 两个方面,应当根据现行国家标准《民用建筑热工设计规范》 GB 50176 中的相关规定进行验算。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '7'), '7.4.3', '本条为新增条文。对民用建筑内建筑设备的隔振降噪设 计作出了规定,主要是从产生噪声房间的位置布置、低噪声低振 动设备选取、设备的隔振、管道隔振隔声、消声处理等各方面着 手, 降低噪声和振动在建筑内传播, 保证噪声敏感房间内的声环 境。相比空气声隔声,设备、管道等引起的振动和固体传声更难 处理,因此将设备房间远离噪声敏感建筑及噪声敏感房间是最有 效的措施。在受条件限制无法做到设备房间远离的情况下,应采 取充分而仔细的隔振隔声措施,不要因为百密而一疏,导致所有 隔振隔声措施前功尽弃。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.1.2', '第1款~第4款根据工程设计中存在的问题,从安全和 卫生方面考虑,提出此要求。 119 第6款为新增条文,主要针对卫生防疫部门对生活给水泵房 内的卫生要求提出的。集水坑不应设在生活给水泵房内,且不应 与生活污水、污水处理站等共用集水坑。生活给水泵房内的地面 及基础应贴地砖,墙面和顶面应采用涂刷无毒防水涂料等措施。', FALSE, '一般性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2.1', '1 集中供暖的优势与热电联产或供暖锅炉房建设规划、 供暖度日数、建筑功能或使用时间等有关。凡有集中供热能力或 邻近电力等工业余热的居住建筑, 宜鼓励采用集中供暖;间歇使 121 用且无须值班供暖的建筑,采用分户供暖系统更易满足个性需 求。值班供暖见现行国家标准《供暖通风与空气调节术语标准》 GB/T 50155。指在非工作时间或中断使用的时间内,为使建筑 物保持最低室温要求的供暖方式(最低室温要求指防冻要求或舒 适要求)。 4室内供暖、室外热力管道投入使用后,直管段势必产生 热膨胀,须根据经验或允许应力计算确定补偿弯或补偿器占用空 间, 避免管道因热膨胀而损毁或导致事故。由于管道所有分支处 均应采用补偿措施,所以室内敷设或管沟、管廊敷设时均应预留 足够的空间便于安装自然补偿弯, 装有补偿器的位置应预留检修 或更换的作业空间。 5 有地下室的建筑,供暖系统的热力人口宜设在地下层的 专用隔间; 无地下室的建筑,可设在首层楼梯下部便于观察的空 间。热力入口见现行国家标准《供暖通风与空气调节术语标准》 GB/T 50155,指室外热网与室内用热系统的连接点及其相应的 调节、计量装置,宜有专用房间或有门锁的空间。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2.2', '1 新风采集口不应设在窝风或易被扬尘、尾气、排气等 污染的区域:且进风口的下缘距室外绿地不宜小于1m或距地坪 不小于2m, 高空排放是指排出的废气不应影响到周边行人或相 邻建筑; 住宅共用排气道底部与供暖管沟、地下室开敞空间或室 外相通,且各户排(烟) 气软管在排气道内延长1m~2m,可防 止户间串气、串声。 4事故排风(emergency ventilation,见现行国家标准《供 暖通风与空气调节术语标准》GB/T 50155)是用于排除或稀释 房间内突然散发的有害物质、有爆炸危险的气体或蒸气的通风方 式。排出的气流不应进入本楼或其他建筑的通风系统。', FALSE, '建议性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.2.3', '1 为了以最低的能源消耗获得建筑使用期间较完美的舒 适性能, 空调系统及其运行方式应尽量符合仅夏季或全年的使用 122 要求。 3 风冷室外机在冬季工况也称空气源热泵;冷却塔等室外 水冷设备难免飘水,应尽可能避免飘向行人或周边建筑, 使用防 冻液的冷却设备, 其飘液对行人、周边建筑或绿地的危害更大。', FALSE, '强制性条文'),
((SELECT id FROM civil_building_chapters WHERE chapter_number = '8'), '8.3.7', '本条文根据现行国家标准《建筑物防雷设计规范》GB 50057 的要求进行编写, 接闪器包括接闪杆、接闪带、接闪线、 129 ≥1mm 地坪 箱(盒) 缆线保护管 缆线保护管 墙(柱) ≥15mm 图 14 暗敷缆线保护管覆盖层最小值示意 接闪网等。', FALSE, '一般性条文')
;

-- 统计信息：共提取 310 条条文
-- 统计信息：共 11 个章节
-- 统计信息：强制性条文 4 条